const { Server } = require('./')

// eslint-disable-next-line new-cap
const uQuik = new Server()

uQuik.get('/*', (request, response) => {
  response.send(`

  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec cursus fermentum est sit amet posuere. Donec sed nisi at libero sollicitudin vestibulum. Phasellus id faucibus leo, sit amet iaculis enim. Donec volutpat pharetra pellentesque. Ut euismod suscipit lectus sed pretium. Suspendisse vel ornare ante. Nam ac neque felis. Donec gravida, nibh porttitor volutpat tincidunt, libero leo convallis metus, vel fermentum nulla mi vel quam. Donec at condimentum dolor. Sed eu dolor nec nulla aliquet egestas. Curabitur fermentum dui lorem, nec interdum urna viverra ac. Nunc tincidunt vel velit in aliquet. Ut finibus magna eu nisi ultrices, id facilisis nulla dictum. Sed vehicula tincidunt ligula at efficitur. Vestibulum lacinia, eros ac placerat vestibulum, ex lectus dignissim enim, sit amet posuere eros diam ut erat.
  
  Integer eu nulla vitae enim placerat finibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque non gravida lectus. Ut condimentum, neque ut sagittis ullamcorper, augue justo consequat ipsum, non varius nunc magna ut velit. Aliquam non feugiat ante, non ullamcorper mi. Vestibulum varius erat lacus, in interdum ante auctor sit amet. Nunc tortor magna, interdum id blandit quis, lacinia sit amet diam. Morbi laoreet rhoncus sem sit amet iaculis. Vestibulum efficitur euismod commodo. Integer tempor eros non orci tristique, quis condimentum felis pellentesque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla sed augue non mi vestibulum finibus. Sed tincidunt mauris nec ex mollis, suscipit venenatis leo hendrerit.
  
  In quis dictum sapien. Aenean at euismod lectus. Sed condimentum leo felis, a euismod augue maximus vel. Mauris elementum non purus vel dignissim. Vestibulum sodales blandit enim, ac maximus arcu. Phasellus sed pulvinar leo. Sed a faucibus mauris. Etiam pretium ante turpis, id aliquam nulla tempus vitae. Praesent mattis rutrum lacus vitae vehicula.
  
  Nulla facilisi. Donec bibendum nec elit vitae pretium. Fusce convallis sapien mauris, sit amet dignissim velit suscipit vel. Duis non imperdiet turpis, et tincidunt erat. Curabitur vitae elit sem. Etiam semper vehicula magna, consectetur lobortis diam. Aliquam et turpis dignissim, tincidunt dolor eu, efficitur elit.
  
  Fusce vulputate ante neque, sollicitudin mollis metus laoreet nec. Donec eget venenatis elit. Etiam nec arcu pharetra, ultricies est sit amet, congue neque. Aenean feugiat, felis non vehicula mattis, nunc ligula laoreet elit, mattis fringilla tortor purus ut urna. Phasellus ligula arcu, tincidunt ac est eu, lacinia pretium ipsum. Nullam bibendum nibh sed varius aliquet. Sed et urna vitae est tempor euismod. Ut efficitur, arcu non dapibus ornare, nunc odio dapibus justo, ac laoreet mauris nisl ut ipsum. Aliquam erat volutpat. Vivamus sit amet volutpat metus. Mauris ac lectus id lacus feugiat ultrices. Quisque elementum, lectus vel consectetur consequat, mi massa imperdiet sapien, in aliquam leo enim at risus. In pharetra, tellus porttitor feugiat malesuada, velit justo euismod turpis, eget mattis enim libero eu arcu. Suspendisse mi lectus, ullamcorper scelerisque quam quis, volutpat aliquam velit.
  
  Vivamus varius blandit sem vel luctus. Donec laoreet rutrum purus, in luctus nulla fringilla a. Nulla eu tempor dolor. Phasellus egestas lacus sed tincidunt commodo. Etiam tristique, elit et mollis tincidunt, nibh dolor porttitor odio, ac maximus risus elit ac quam. Quisque et consequat risus. Nullam tristique dolor a diam rhoncus facilisis consequat id augue. Vestibulum facilisis sodales ipsum, sit amet auctor libero pharetra vitae. Aenean quis tincidunt libero, non sagittis neque. Ut eget elit ut sem tristique vehicula.
  
  Donec leo massa, bibendum in nisi eu, pretium varius erat. Curabitur id sagittis urna. Nunc sed eros libero. Sed sit amet convallis tortor, sed auctor leo. In luctus vitae purus at mattis. Duis congue convallis urna, ut condimentum erat mollis ut. Curabitur commodo posuere fringilla. Donec luctus, velit quis maximus placerat, est sapien pulvinar nulla, eget tincidunt lectus augue at lacus. Donec vitae blandit erat. Nulla a ex quis arcu cursus finibus. Sed enim dolor, laoreet non diam eget, ullamcorper lobortis nunc. Duis luctus nulla non elit gravida dignissim. Sed sed scelerisque libero. Maecenas semper vitae urna non luctus. Etiam tempor semper rhoncus. Aliquam pulvinar neque ante, at tincidunt libero laoreet eu.
  
  Quisque sollicitudin rhoncus fringilla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum placerat metus eu porttitor. Duis interdum, neque at semper consequat, libero velit finibus mauris, fringilla ullamcorper dolor turpis sit amet enim. Fusce sed tempor turpis, aliquet sodales turpis. Maecenas eleifend posuere efficitur. Suspendisse id tortor placerat, laoreet nisi a, sodales ante. Duis dignissim leo odio, sed pellentesque odio pretium eget. Vestibulum in orci nec libero egestas condimentum. Suspendisse mattis, erat ac tincidunt rutrum, justo leo suscipit libero, vel porttitor quam dui sit amet mauris. Vestibulum maximus posuere nisl quis mollis. Vivamus dolor ante, volutpat sed luctus sit amet, congue et tortor. Phasellus massa mi, rutrum sit amet nulla nec, auctor viverra ligula.
  
  Duis tincidunt iaculis iaculis. Donec placerat, ante a porta sodales, magna sem vehicula nulla, sit amet pellentesque sem neque porttitor magna. Nulla mauris sem, hendrerit et egestas sit amet, feugiat accumsan urna. Nullam et orci fermentum, cursus augue et, consectetur neque. Ut non nisl quis dui suscipit tempus. Sed interdum lacus sit amet libero convallis, eu ullamcorper leo vulputate. In vulputate enim ut turpis tincidunt, eget lacinia ipsum tristique. Vivamus bibendum felis in tortor aliquet mollis id vel nisi. Fusce erat lectus, iaculis non augue pellentesque, scelerisque laoreet neque. Duis interdum nibh aliquam metus euismod, vel vestibulum diam pellentesque. Etiam velit sem, interdum sit amet dapibus eu, ullamcorper vitae quam. Vivamus vestibulum magna at mi posuere dictum. In diam mi, elementum a dictum ut, luctus nec nibh. Nunc a venenatis sapien, vitae rutrum lectus.
  
  Vestibulum nunc lectus, mollis vulputate commodo eu, euismod sed dolor. Fusce enim mauris, rhoncus sit amet ornare a, tempor eu leo. Fusce rhoncus, quam rhoncus fermentum sagittis, leo nisl tincidunt libero, non sagittis magna quam egestas nunc. Mauris eget ante vitae risus bibendum vulputate. Etiam vitae augue commodo, tincidunt libero eget, sodales est. Curabitur varius quam gravida magna mattis laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In eleifend sapien ex, id pellentesque nisi ultrices a. Sed quis tempus orci. Curabitur tincidunt lacus at mi faucibus posuere. Donec faucibus pretium tellus at volutpat.
  
  Integer urna dui, ultrices et lectus ut, bibendum lobortis turpis. In porttitor interdum rutrum. Quisque ultricies eget odio eu tincidunt. Integer maximus ligula enim, a maximus nisl consequat ac. Donec id nibh sed lacus dictum volutpat a in odio. Morbi leo mi, egestas laoreet nulla nec, accumsan consequat sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer feugiat nulla nec neque dictum hendrerit. Sed sagittis, leo eget convallis egestas, diam mauris sagittis arcu, eu porta felis enim vitae tortor. Phasellus gravida arcu dolor, sed pulvinar dolor suscipit id.
  
  Curabitur in facilisis lacus. Aliquam ullamcorper libero vel mi ornare, id commodo orci vulputate. Etiam sollicitudin aliquet scelerisque. Morbi ultrices nibh vel nibh porttitor, quis convallis ligula ornare. Maecenas viverra orci eget ligula tincidunt bibendum. Etiam efficitur vestibulum efficitur. Duis nec sollicitudin sem, vel porta enim. Integer eget dui ac turpis dictum vehicula. Vivamus nec orci a felis varius ultrices. Ut hendrerit blandit sapien a vulputate.
  
  Vestibulum vestibulum rutrum rutrum. Proin finibus, quam in vulputate dapibus, sem libero rhoncus odio, non finibus enim tellus ac tellus. Pellentesque consequat in dolor quis eleifend. Phasellus mollis neque aliquet turpis euismod dapibus. Quisque id arcu ut est consectetur ornare. Ut a mi bibendum, ullamcorper nisi sit amet, ullamcorper ex. Donec pretium in nisl eu vulputate. Integer semper purus massa, id euismod tellus vehicula vel. Suspendisse consequat accumsan turpis, vitae iaculis lorem volutpat quis. Mauris felis dolor, volutpat viverra faucibus quis, elementum in nunc. Nunc sed iaculis velit, sed rhoncus nisl.
  
  Ut vel neque ornare tellus efficitur viverra a et metus. Nullam faucibus interdum suscipit. Morbi vehicula ante vitae risus congue, id malesuada odio volutpat. Nulla eleifend faucibus ipsum et pharetra. In vestibulum tempor efficitur. Duis interdum augue vehicula nibh lacinia, at placerat metus finibus. Nulla quam lorem, sodales in dictum ac, rutrum quis enim. Nunc nec arcu sed est volutpat imperdiet suscipit ut dui. Ut sed pharetra neque. In magna risus, vehicula vel metus quis, tincidunt laoreet lacus.
  
  Nam bibendum eros tortor, nec vehicula risus laoreet vel. Integer rhoncus blandit ex, nec vulputate erat. Nulla placerat, dui a posuere varius, dolor nisl accumsan sem, vel imperdiet ex metus ac justo. Donec tincidunt, arcu dignissim laoreet sollicitudin, nisi libero pulvinar sem, non pellentesque massa nulla in nibh. Nullam pulvinar mi ac dictum finibus. Integer bibendum vestibulum metus, in vehicula est fringilla eget. Nullam lacinia aliquet lacus nec sodales. Vivamus venenatis leo tortor, sit amet ultricies leo tempus ac. Sed nulla leo, malesuada tincidunt ornare eu, lobortis non ex. Cras consectetur vel leo non porta. Mauris malesuada semper massa ac vulputate. Integer lobortis quis turpis a porta. Praesent luctus pharetra diam id cursus. Pellentesque et nulla in arcu luctus elementum. Aliquam at dui in nisl cursus molestie. Morbi at gravida enim.
  
  Morbi convallis vitae nulla ut tincidunt. Praesent in ullamcorper sem, vel venenatis massa. Cras et leo mollis quam aliquam dapibus eget eget ligula. Quisque facilisis luctus velit, a vestibulum metus. Curabitur posuere ipsum vel orci mollis, in convallis urna malesuada. Etiam eleifend ipsum est, ac scelerisque mi tincidunt eu. Aliquam erat volutpat. Phasellus laoreet dolor at vulputate posuere. Suspendisse neque odio, sodales non porttitor ornare, efficitur at est. Aliquam ac feugiat libero, vel elementum nisi. In sed pellentesque metus. Phasellus sed ligula porttitor, suscipit mi in, fringilla libero. Sed consectetur consectetur tellus at suscipit. Praesent pulvinar, mauris cursus sodales vestibulum, sapien eros commodo eros, a pharetra urna risus ut massa. Nunc condimentum lacinia accumsan. Vestibulum est ligula, vestibulum vel venenatis ac, pharetra vitae sapien.
  
  Vivamus massa magna, dignissim ut pulvinar ut, facilisis sed ante. Maecenas at mollis sapien. Proin molestie nisi imperdiet magna lobortis, sit amet consectetur risus vehicula. Donec gravida, quam nec vestibulum vehicula, lorem dolor faucibus ipsum, pulvinar sagittis massa ipsum sed ligula. Curabitur facilisis mi tortor, sit amet condimentum nibh auctor non. Vivamus facilisis tempor massa lacinia malesuada. Quisque vulputate neque at dapibus accumsan. Integer consequat, orci sit amet posuere pellentesque, felis enim convallis sem, non vulputate quam nisl et nisl.
  
  Mauris tincidunt mollis urna, in volutpat tortor gravida non. Quisque est dui, tincidunt ut sagittis et, tincidunt sit amet lectus. Mauris convallis eleifend felis ac porttitor. Aliquam erat volutpat. Morbi porttitor scelerisque nulla ac malesuada. Quisque est libero, commodo ut ligula at, condimentum consectetur neque. Nulla pulvinar orci sit amet vulputate lobortis. Nullam bibendum sollicitudin felis pellentesque viverra. Etiam scelerisque euismod erat, ut eleifend velit imperdiet consectetur. Praesent vestibulum, felis eu aliquet pellentesque, metus arcu condimentum ante, a efficitur dolor purus quis enim.
  
  Fusce pulvinar sollicitudin scelerisque. Sed pellentesque, odio nec ultrices luctus, velit sem auctor est, quis venenatis ante mi nec nisl. Proin id lectus sit amet dolor varius aliquet ultrices blandit nulla. Vestibulum gravida mattis nunc, nec luctus neque luctus sed. Aenean eget metus diam. Integer accumsan viverra tortor, ut tempus tortor congue a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sagittis arcu non elit suscipit, tincidunt posuere dolor tempus. Aliquam fermentum odio eget dictum semper.
  
  Donec ac consequat lacus, vel fermentum orci. Etiam mollis commodo nulla, at molestie ipsum faucibus sagittis. Etiam dui risus, dignissim in porttitor quis, venenatis ac ante. Morbi quis felis nec nulla laoreet mattis. Aenean enim sapien, suscipit eget massa mollis, pharetra congue metus. Proin pretium aliquam quam eu suscipit. Nam ac est id sapien feugiat aliquam in eget magna. Suspendisse finibus ex sit amet ante porta dignissim ut at diam. Nam nisi est, mattis nec accumsan vitae, condimentum at neque. Nunc luctus risus vitae neque auctor dapibus. Proin malesuada sodales metus quis laoreet. Vestibulum et risus eu dui scelerisque vehicula vel a nulla. Etiam placerat sed nisi finibus volutpat.
  
  Phasellus vehicula risus vitae felis eleifend mattis. Integer volutpat dolor vel libero vulputate, non dictum nisl faucibus. Phasellus facilisis euismod pretium. Curabitur et nibh nulla. Sed luctus metus est, eu vestibulum quam iaculis id. Vestibulum dapibus, elit ut feugiat fermentum, sapien sapien porta justo, at posuere lectus risus nec erat. Curabitur imperdiet ipsum at orci elementum, vel porttitor enim imperdiet. Ut vestibulum bibendum velit nec porttitor. Fusce mi metus, vulputate sed commodo nec, mollis ut sapien. Sed scelerisque id dui eu lacinia.
  
  In pharetra odio ipsum, sed dapibus massa auctor non. Mauris feugiat felis et lacus tempor tempus. Aenean nec dictum arcu. In interdum sem nunc, ut scelerisque urna vestibulum eu. Pellentesque venenatis tortor vitae pharetra elementum. Vivamus ultrices mollis massa, a blandit erat lobortis quis. Suspendisse sit amet aliquam augue, in condimentum odio. Suspendisse lacinia erat vel ligula consectetur faucibus. Vestibulum nibh ante, iaculis quis risus in, gravida cursus ante. Suspendisse potenti. Curabitur justo ipsum, varius et odio ut, faucibus sollicitudin massa. Mauris a fermentum nisl. Etiam et suscipit urna, quis semper lorem.
  
  Integer laoreet nisi urna, a porta ante venenatis a. Ut cursus sapien ut nulla egestas malesuada. Integer auctor mi ut augue facilisis rhoncus. Proin ac tincidunt nunc. Fusce in odio at mauris tincidunt aliquet. Quisque interdum libero turpis, ut porttitor metus molestie et. Proin vitae quam eu arcu sollicitudin lobortis eu ut justo. Curabitur finibus ac sem eu ornare. Mauris sit amet porta purus, et aliquam magna.
  
  Mauris ut nisi pulvinar, aliquam nulla pretium, convallis nibh. Sed scelerisque malesuada dolor in pulvinar. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla vulputate risus dignissim nunc pretium, id dapibus justo varius. Curabitur maximus semper tellus, at auctor enim. Aliquam facilisis, mi vel porttitor pulvinar, lectus est venenatis massa, ut pellentesque leo eros nec ligula. Suspendisse rhoncus sapien ac justo faucibus porta. Suspendisse potenti. Donec at lacus velit. In vel sem eget metus varius sagittis ut iaculis mi. Mauris vulputate vitae ex facilisis dictum. Morbi maximus mi viverra dolor finibus interdum. Phasellus blandit efficitur congue.
  
  Praesent pretium euismod elit at fermentum. Phasellus in odio ligula. Pellentesque sed bibendum risus. Cras placerat dolor vel tellus hendrerit viverra. Pellentesque lobortis lectus elit, nec aliquet nulla hendrerit a. Nunc commodo euismod nisl vitae elementum. Sed ante est, ultricies sit amet felis vitae, feugiat tincidunt enim. Cras pharetra id eros eu condimentum. Pellentesque elementum lacus ut neque tempor tincidunt. Mauris fermentum turpis eget diam aliquam, in euismod magna pellentesque.
  
  Proin eu posuere nibh. Aenean viverra, mauris sed placerat luctus, ante orci laoreet ante, nec varius risus mauris vitae massa. Fusce gravida non metus vitae ultrices. Aenean mattis eros vel ex vulputate, id sodales massa porta. Pellentesque venenatis risus nec magna scelerisque, et hendrerit neque tempus. Nunc mattis eros finibus nisl vehicula, id hendrerit mauris aliquam. Nam consequat, risus ac dapibus faucibus, neque dui consectetur tortor, at mattis sapien augue et purus.
  
  Vestibulum lorem urna, venenatis nec dapibus sit amet, consectetur quis magna. Cras id nunc dui. Maecenas vehicula eros nunc, in ornare tellus porta ut. Vestibulum auctor ipsum sit amet odio lacinia lobortis sit amet sit amet metus. Integer aliquam leo eu metus blandit, in pharetra dolor efficitur. Aenean nunc sapien, malesuada sit amet dapibus et, convallis vel ex. Curabitur accumsan elit mi.
  
  Morbi sodales, ex ut fermentum accumsan, lacus sem iaculis orci, quis accumsan lorem turpis id massa. Cras efficitur elit turpis, quis vehicula lorem tincidunt in. Nam iaculis turpis et nisi consequat volutpat. Curabitur purus quam, mattis nec lorem sit amet, viverra porta libero. Morbi bibendum pulvinar justo sed efficitur. Mauris a risus non felis lobortis congue. Mauris ac feugiat augue, semper congue magna. Aenean hendrerit massa quis diam tincidunt, at lobortis sem posuere. Aliquam erat volutpat. Integer bibendum diam vitae consequat sollicitudin. Aliquam varius efficitur nisi in dapibus. Nulla sodales mauris quis rutrum faucibus.
  
  Ut eget magna et magna dictum luctus in id odio. Quisque blandit, augue in consectetur interdum, lorem nisl ultricies nisl, sed consectetur magna elit quis mi. Nulla metus massa, maximus sit amet elit sit amet, elementum euismod mauris. Duis blandit nunc nec tincidunt fringilla. Donec sit amet interdum nunc, eget tempor magna. Aliquam accumsan mattis nisl, vitae efficitur libero auctor eget. Sed vel velit pulvinar, convallis diam faucibus, interdum mauris. Aenean id elit leo. Nam a accumsan sapien. Sed erat ante, dictum in nibh eget, aliquam convallis arcu. Nam viverra nisl ac fermentum scelerisque. Vestibulum tempor risus a sapien aliquam, ut luctus mi pretium. Curabitur vel justo purus. Quisque vitae quam condimentum, tristique lorem vel, finibus augue.
  
  Aliquam erat volutpat. Morbi egestas, tortor eu euismod lacinia, ligula purus vehicula metus, at faucibus magna justo vitae sapien. Proin et purus eu sem gravida pretium. Integer varius ornare varius. Sed faucibus viverra auctor. Suspendisse eget lacus laoreet eros posuere molestie. Aliquam sagittis dapibus dolor, ac hendrerit elit accumsan sed. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
  
  Pellentesque ut tortor arcu. Donec a auctor nulla. In ornare lectus in est vestibulum, id sagittis odio hendrerit. Aenean id ipsum in purus sodales luctus. Cras ut lectus sed eros tincidunt blandit ornare placerat tellus. Duis vestibulum vitae ex id sodales. Sed pretium leo finibus nunc luctus, non aliquam nulla tempor. Aenean id leo quis justo elementum luctus. Proin viverra magna at accumsan finibus. Phasellus a elit ligula. Vestibulum ac elit consequat, auctor diam vitae, consectetur mi. Nam tincidunt, odio vel tincidunt posuere, mauris justo posuere est, vel egestas metus sapien sit amet turpis. Sed urna felis, pretium at mattis sed, dignissim sed augue. Ut pellentesque nunc at imperdiet ultrices. Morbi non urna nisi. Nunc dapibus nunc eu massa semper finibus.
  
  Phasellus bibendum et nibh quis lobortis. Suspendisse eget pellentesque justo, vel fermentum mi. Mauris viverra dolor vitae metus tempor vestibulum ac at ex. Donec nec lectus vel quam pharetra facilisis. Proin felis nisi, facilisis ut quam ut, sollicitudin dapibus velit. Cras egestas scelerisque mauris, a ornare arcu aliquam vehicula. Nam nec tempor arcu. Duis nec vestibulum tortor, at maximus eros. Sed fermentum, lectus eget porttitor mattis, libero lectus vehicula orci, a pharetra nisl massa efficitur libero. Suspendisse eget pellentesque magna. Ut non finibus nisi, in scelerisque mi. Ut elementum, justo ut sodales dictum, dolor sapien mollis justo, non commodo magna sem nec eros. Sed ut quam non quam blandit posuere non suscipit dolor. Nam eu odio non lacus fringilla volutpat. Sed sit amet odio mauris. Quisque placerat lectus sit amet felis tempus ultricies sed eu lacus.
  
  Duis gravida ligula felis, id venenatis ipsum viverra vel. Vivamus felis erat, facilisis id nisi quis, maximus facilisis orci. Aenean ac nunc placerat, tincidunt massa vitae, dapibus erat. Ut quis urna dolor. Etiam quis congue mauris. Nam feugiat suscipit velit sed imperdiet. Maecenas vestibulum magna elit, eget laoreet est tempus et. Integer erat felis, molestie sed ornare ut, vestibulum ac mi. Quisque sed tincidunt velit. Proin ultrices orci nisi. Ut blandit eleifend viverra. Quisque ac tortor mattis, efficitur lacus vel, consequat arcu.
  
  Fusce eget sapien eu nibh faucibus interdum ut nec elit. Donec quis ex odio. Cras bibendum blandit imperdiet. Suspendisse turpis augue, aliquet non tempor sed, mollis vel lorem. Suspendisse lorem magna, hendrerit a massa sed, faucibus condimentum enim. Donec interdum sit amet velit et rhoncus. Sed nec nunc diam.
  
  Morbi convallis id ipsum eget condimentum. Aliquam nec sollicitudin elit. Sed dolor mi, vulputate sed nisi a, tincidunt mollis urna. Etiam eu fringilla mi. Nam non lectus eu quam iaculis pellentesque et eget quam. Cras quis posuere ipsum. Integer venenatis urna erat, nec ullamcorper enim ullamcorper vitae. Maecenas mollis in est a dapibus. Pellentesque vel quam tincidunt, ornare diam dictum, iaculis augue. Vivamus eget mollis velit. Fusce ac nisi facilisis neque placerat vulputate. Vivamus pulvinar luctus ornare.
  
  Phasellus blandit lorem vestibulum est bibendum egestas. Sed et laoreet lacus. Curabitur nulla dolor, gravida vitae mauris eu, convallis luctus massa. In fermentum iaculis turpis, et hendrerit justo rutrum eget. Ut ac augue eu augue malesuada venenatis. Suspendisse velit tellus, sagittis nec egestas id, convallis non odio. Quisque vitae nulla gravida, pellentesque velit sed, commodo metus. Pellentesque maximus turpis id elit fringilla facilisis. Phasellus vel tempus lorem. Donec egestas nibh nec mi gravida, ac malesuada tellus euismod.
  
  Nulla facilisi. Nam felis nunc, malesuada quis tellus eu, tempus euismod leo. Suspendisse aliquam tortor eget odio egestas tincidunt. Cras vulputate lorem sit amet auctor ultrices. Nulla quis cursus metus. Pellentesque ultricies id arcu ac pellentesque. Nunc sodales lorem magna, et iaculis diam luctus at. Donec condimentum imperdiet nisi, ut sodales nibh tincidunt eget. Sed auctor a est eu egestas. Praesent nec magna nec sem facilisis vulputate. Fusce non fringilla purus. Nam risus orci, rutrum ut purus sit amet, dignissim bibendum erat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec scelerisque lacinia felis, vel faucibus metus ullamcorper id.
  
  Proin ut lacus non purus scelerisque lobortis et quis nulla. Curabitur quis bibendum elit. In quis pharetra nibh, sed vestibulum augue. Morbi at quam augue. Vestibulum ac mi sapien. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Vivamus pellentesque id nibh ac pulvinar. Phasellus suscipit urna ac ipsum tempus, non lacinia elit porta. Donec efficitur sem tortor, sed sollicitudin libero lacinia eget. Fusce ultrices sem ac pulvinar sagittis. Sed venenatis volutpat dolor, in sodales quam sollicitudin sed. Maecenas mauris leo, dictum a magna ut, ultricies lacinia ante. Maecenas nec placerat libero, at euismod velit. Cras efficitur pretium felis, cursus iaculis lectus dapibus in. Aenean quis sodales tortor.
  
  Ut ultricies gravida ex, id congue lectus efficitur vehicula. Cras vulputate vulputate purus eu dictum. Donec auctor arcu in libero pulvinar, quis fringilla velit varius. Suspendisse potenti. Vestibulum et aliquet est, ac tincidunt odio. Maecenas vel ultrices augue, sit amet tempus ante. Ut in volutpat urna, vitae interdum ante.
  
  Cras sit amet ex scelerisque, luctus eros quis, consectetur enim. Maecenas suscipit mi at scelerisque pellentesque. Pellentesque iaculis commodo ornare. Sed mollis pretium massa sit amet congue. Maecenas porta diam vel diam ullamcorper, at suscipit turpis cursus. Suspendisse ultrices dapibus egestas. Donec ultricies mi id purus volutpat pellentesque. Nunc nec lobortis odio. Donec sollicitudin sodales nibh id consequat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi sagittis sem vitae facilisis mattis. Suspendisse dapibus porta orci tincidunt bibendum. Nam non ligula in nisi eleifend luctus. Vivamus semper, lectus ultrices laoreet sodales, lacus ante porta tortor, vel venenatis diam mi sit amet nisi.
  
  Pellentesque tincidunt felis nunc, vel ullamcorper eros gravida vitae. Nullam dictum viverra arcu a euismod. Etiam lobortis tellus sem. Integer elit est, blandit non nisi ut, malesuada imperdiet elit. Sed in ligula malesuada, volutpat libero vel, sodales dolor. Quisque interdum metus leo, pretium blandit arcu blandit sed. Mauris euismod, erat vitae scelerisque convallis, velit sapien efficitur risus, ultricies dignissim orci est in lorem. Donec aliquam risus eu magna maximus aliquam id eget dui. Curabitur in turpis leo. Suspendisse tincidunt nisi quis diam suscipit sodales. Aenean et volutpat ipsum, nec molestie risus. In ac tortor ac est pulvinar congue vel ac odio. Nam sodales augue vel risus consectetur, id pharetra felis suscipit.
  
  Sed facilisis, lectus sed euismod aliquet, arcu risus rutrum erat, placerat lacinia justo magna a metus. Etiam rutrum ante lorem, egestas pulvinar lacus accumsan in. Vestibulum vel risus id ante pretium mollis. Vestibulum non molestie justo. In maximus dapibus massa non lacinia. Etiam auctor ultricies eros, sit amet lacinia leo luctus et. Praesent erat mi, ornare in gravida vel, euismod sed dolor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus ac eleifend mi, vitae blandit sem. Maecenas facilisis id est sit amet sollicitudin.
  
  Nam a tellus sit amet quam rhoncus placerat. Quisque et odio eget augue mattis imperdiet vulputate vel enim. Vivamus feugiat dui erat, ut pretium elit lobortis sed. Sed convallis venenatis neque sed ullamcorper. Pellentesque a gravida odio. Fusce auctor ligula eu risus hendrerit tempus. Donec molestie justo pulvinar erat gravida rhoncus ut ut dui. Aenean vel tempus metus. Praesent ac euismod libero. Maecenas sollicitudin tempus tellus at ornare. Suspendisse potenti. Nunc varius pulvinar justo. Praesent interdum erat sit amet orci ultrices, eu consequat mauris lobortis. Nullam tristique neque nibh, ut vehicula arcu ornare tristique. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;
  
  Aliquam vulputate aliquam semper. Sed viverra placerat vehicula. Sed non aliquam odio, quis rhoncus dolor. Maecenas placerat enim elit, eget faucibus ipsum ultrices sed. Pellentesque cursus mauris ut luctus faucibus. Ut consequat velit nulla, eu suscipit leo pretium eu. Etiam rhoncus euismod sem, nec vulputate quam tincidunt in. Nullam commodo mi ligula. Aliquam nec posuere dui. Cras ut sem molestie sem aliquam rhoncus. Cras non sapien euismod, malesuada lectus imperdiet, molestie mauris. Etiam ut turpis vitae augue euismod porta a et odio.
  
  In rutrum vel tellus eu vehicula. Nulla scelerisque tristique turpis, nec feugiat nisl blandit at. Fusce pretium viverra felis in mattis. Suspendisse potenti. Phasellus eget blandit velit. Nunc accumsan, enim in eleifend facilisis, enim eros semper orci, et tempor velit ex eu turpis. Maecenas mattis lorem in placerat imperdiet. Vivamus lacinia ex sit amet justo consequat, quis mollis urna faucibus. Ut ut venenatis augue, sed hendrerit magna. Morbi id sapien maximus, molestie tortor id, aliquet nunc. Vestibulum ex lacus, pharetra vel sodales ut, pharetra sit amet tortor. Sed non felis ut ante hendrerit mollis at sit amet nunc.
  
  Donec venenatis nibh at nibh cursus vulputate. Praesent cursus felis sed purus vehicula molestie. Nam sed enim id massa tempus sagittis. Sed fermentum lectus sed condimentum ornare. Nulla maximus accumsan nunc ut finibus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed efficitur nunc id fermentum ultricies.
  
  Etiam congue luctus felis, vitae aliquam erat elementum id. Nam tortor odio, ultricies at rhoncus quis, feugiat facilisis nulla. Donec in nisi condimentum, rhoncus sem eu, varius nibh. Proin malesuada felis et quam elementum, vel bibendum nunc congue. Pellentesque pulvinar velit vehicula consectetur maximus. Aliquam lacinia risus et congue rutrum. Aenean sagittis felis sed nibh dignissim dignissim. Suspendisse gravida volutpat ligula, a placerat metus mattis sed. In dictum velit id ligula iaculis egestas. Phasellus nulla elit, lacinia id turpis id, ornare consequat lorem. Vivamus ac felis eget orci aliquet dictum sed ac risus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Maecenas tempor vulputate scelerisque. Praesent sed lectus ac enim ultricies bibendum eu vitae turpis. Quisque elementum augue nec velit elementum dignissim.
  
  Etiam volutpat volutpat lacus, vitae sollicitudin neque porta ut. Nunc at nisl mi. Vestibulum luctus lorem nunc, sit amet ultrices nisl sodales sit amet. Sed venenatis, mauris vitae cursus faucibus, odio velit imperdiet tortor, in accumsan ipsum purus et tortor. Vestibulum posuere posuere feugiat. Fusce id pharetra ipsum, a venenatis odio. Sed vitae dui bibendum, blandit velit sit amet, posuere tortor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras varius libero sapien, sit amet dapibus tortor ornare eu. Sed ut fermentum orci. Aliquam sollicitudin neque nec nisi tempor aliquet. Sed sit amet consectetur ipsum. Donec nec urna neque. Nullam in placerat ligula. Praesent id turpis auctor, rhoncus dolor at, fermentum augue.
  
  Quisque vel nibh elementum, tincidunt turpis eget, ullamcorper nisl. Etiam libero magna, aliquet quis lobortis sodales, blandit sit amet velit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque gravida vel odio in molestie. Etiam sollicitudin faucibus neque, aliquet maximus nibh fringilla ut. Fusce mollis, est fermentum feugiat laoreet, leo risus consectetur magna, sit amet ultrices elit risus quis neque. Proin et urna sit amet lorem rhoncus sagittis. Nulla nisi dui, fringilla et ligula blandit, convallis finibus lectus. Suspendisse potenti. Proin hendrerit rhoncus ante, id luctus nibh rutrum congue. Donec non interdum est, eu rhoncus mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ullamcorper a purus at iaculis.
  
  Suspendisse ultricies consectetur lectus sed pretium. Ut sit amet odio non quam congue tempus ac in velit. Cras et lacus a sapien ullamcorper imperdiet vel sit amet tortor. Duis rhoncus ante lectus, vitae imperdiet turpis ultrices ut. Nullam malesuada euismod lorem, in iaculis eros porttitor eget. Vivamus ac posuere massa. Cras eu facilisis enim. Aenean vitae odio vehicula, imperdiet nisi eu, commodo velit. Mauris ultrices vitae elit et pulvinar. Proin ultricies malesuada aliquet.
  `)
})

uQuik.listen(5000, '127.0.0.1')
  .then((socket) => console.log('[Example] Server started'))
  .catch((error) => console.log('[Example] Failed to start a server', error))
